# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SNLO 
SEOTitle: snlo的博客 | snlo 
header-img: img/home-bg.png
email: snloveydus@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  APP描述
keyword: "iOS, APP"
url: "https://snlo.app/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# avatar and Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: /img/favicon.ico


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "APP Developer <br/> 未知的我们向着未知的世界出发"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# SNS settings
weibo_username:  snloveydus
zhihu_username:  SNLO
github_username: snlo

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: db0469bd2240fc017d78                            #生成的clientID
  clientSecret: 62b65779044955f7d44eacd13a748e4fc3fd2e70    #生成的clientSecret
  repo: snlo.github.io    #仓库名称
  owner: snlo    #github用户名
  admin: snlo
  # distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Friends
friends: [{
  title: "snlo's github",
  href: "https://github.com/snlo"
}]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
